const fs = require('fs');

const content = [
  'import { useEffect, useRef } from "react";',
  'import gsap from "gsap";',
  '',
  'export default function HeroIllustration() {',
  '  const containerRef = useRef(null);',
  '',
  '  useEffect(() => {',
  '    const prefersReduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;',
  '    if (prefersReduced) return;',
  '',
  '    const ctx = gsap.context(() => {',
  '      // Tree branches reveal',
  '      gsap.fromTo(',
  '        ".tree-branch",',
  '        { strokeDasharray: 2500, strokeDashoffset: 2500 },',
  '        { strokeDashoffset: 0, duration: 4, ease: "power2.out", delay: 0.2 }',
  '      );',
  '',
  '      // Character fade in',
  '      gsap.fromTo(',
  '        ".character-fade",',
  '        { opacity: 0, y: 30 },',
  '        { opacity: 1, y: 0, duration: 1.5, ease: "power2.out", delay: 1 }',
  '      );',
  '',
  '      // Fade in canopy clusters (optimized stagger)',
  '      gsap.fromTo(',
  '        ".glow-leaf",',
  '        { opacity: 0, scale: 0 },',
  '        { opacity: 1, scale: 1, duration: 1.5, stagger: 0.002, ease: "back.out(1.2)", delay: 1.5 }',
  '      );',
  '',
  '      // Floating embers',
  '      gsap.fromTo(',
  '        ".float-particle",',
  '        { opacity: 0, y: 20 },',
  '        {',
  '          opacity: 0.8,',
  '          y: -200,',
  '          duration: "random(4, 8)",',
  '          repeat: -1,',
  '          yoyo: false,',
  '          stagger: 0.15,',
  '          ease: "sine.inOut"',
  '        }',
  '      );',
  '    }, containerRef);',
  '',
  '    return () => ctx.revert();',
  '  }, []);',
  '',
  '  const canopyCenters = [',
  '    { x: -50, y: 200 },',
  '    { x: 50, y: 300 },',
  '    { x: 150, y: 150 },',
  '    { x: 280, y: 80 },',
  '    { x: 420, y: 180 },',
  '    { x: 600, y: 280 },',
  '    { x: 750, y: 180 },',
  '    { x: 850, y: 350 },',
  '  ];',
  '',
  '  const leaves = [];',
  '  let id = 0;',
  '  ',
  '  canopyCenters.forEach((center) => {',
  '    const clusterSize = 32;',
  '    for (let i = 0; i < clusterSize; i++) {',
  '      const radius = Math.random() * 100;',
  '      const angle = Math.random() * Math.PI * 2;',
  '      const cx = center.x + Math.cos(angle) * radius;',
  '      const cy = center.y + Math.sin(angle) * radius;',
  '      ',
  '      const r = 4 + Math.random() * 8;',
  '      const colorRandom = Math.random();',
  '      ',
  '      let gradientId, coreColor;',
  '      if (colorRandom > 0.85) {',
  '        gradientId = "url(#glowTeal)";',
  '        coreColor = "#CCFBF1";',
  '      } else if (colorRandom > 0.70) {',
  '        gradientId = "url(#glowPink)";',
  '        coreColor = "#FAE8FF";',
  '      } else {',
  '        gradientId = "url(#glowGold)";',
  '        coreColor = "#FFF4D6";',
  '      }',
  '      ',
  '      const swayDuration = 3 + Math.random() * 4;',
  '      const pulseDuration = 3 + Math.random() * 3;',
  '      const delay = Math.random() * -5;',
  '',
  '      leaves.push({ id: id++, cx, cy, r, coreColor, gradientId, swayDuration, pulseDuration, delay });',
  '    }',
  '  });',
  '',
  '  const embers = Array.from({ length: 30 }).map((_, i) => ({',
  '    id: i,',
  '    cx: -50 + Math.random() * 900,',
  '    cy: 250 + Math.random() * 400,',
  '    r: 1 + Math.random() * 3,',
  '    color: Math.random() > 0.5 ? "url(#glowGold)" : "url(#glowTeal)"',
  '  }));',
  '',
  '  return (',
  '    <div ref={containerRef} className="relative w-full h-full flex items-center justify-center overflow-visible">',
  '      <svg',
  '        className="absolute inset-0 w-full h-full opacity-100 overflow-visible"',
  '        viewBox="-100 0 1100 1000"',
  '        fill="none"',
  '        xmlns="http://www.w3.org/2000/svg"',
  '        style={{ transform: "scale(1.3) translateX(-5%)" }}',
  '      >',
  '        <defs>',
  '          <linearGradient id="branchGradient" x1="500" y1="900" x2="400" y2="100" gradientUnits="userSpaceOnUse">',
  '            <stop offset="0%" stopColor="#8B6F1F" />',
  '            <stop offset="50%" stopColor="#D4AF37" stopOpacity="0.9" />',
  '            <stop offset="100%" stopColor="#FFF4D6" stopOpacity="1" />',
  '          </linearGradient>',
  '',
  '          {/* High performance radial gradients instead of expensive SVG filters */}',
  '          <radialGradient id="glowGold" cx="50%" cy="50%" r="50%">',
  '            <stop offset="0%" stopColor="rgba(212, 175, 55, 0.8)" />',
  '            <stop offset="100%" stopColor="rgba(212, 175, 55, 0)" />',
  '          </radialGradient>',
  '          <radialGradient id="glowTeal" cx="50%" cy="50%" r="50%">',
  '            <stop offset="0%" stopColor="rgba(45, 212, 191, 0.8)" />',
  '            <stop offset="100%" stopColor="rgba(45, 212, 191, 0)" />',
  '          </radialGradient>',
  '          <radialGradient id="glowPink" cx="50%" cy="50%" r="50%">',
  '            <stop offset="0%" stopColor="rgba(217, 70, 239, 0.8)" />',
  '            <stop offset="100%" stopColor="rgba(217, 70, 239, 0)" />',
  '          </radialGradient>',
  '        </defs>',
  '',
  '        {/* 3D Trunk Shadow - Using opacity instead of filter */}',
  '        <g stroke="#000000" strokeWidth="22" strokeLinecap="round" strokeLinejoin="round" className="tree-branch opacity-50" style={{ transform: "translateX(5px) translateY(5px)" }}>',
  '          <path d="M450 900 Q 400 600, 280 450 Q 150 350, -50 200" />',
  '          <path d="M420 600 Q 550 450, 600 280" strokeWidth="18" />',
  '          <path d="M360 520 Q 420 350, 420 180" strokeWidth="16" />',
  '          <path d="M250 420 Q 150 300, 150 150" strokeWidth="14" />',
  '          <path d="M500 450 Q 650 250, 850 350" strokeWidth="14" />',
  '          <path d="M600 350 Q 700 250, 750 180" strokeWidth="12" />',
  '          <path d="M120 300 Q 50 250, 50 300" strokeWidth="10" />',
  '          <path d="M350 250 Q 320 150, 280 80" strokeWidth="10" />',
  '        </g>',
  '',
  '        {/* Tree Trunk & Branches */}',
  '        <g stroke="url(#branchGradient)" strokeWidth="20" strokeLinecap="round" strokeLinejoin="round" className="tree-branch">',
  '          <path d="M450 900 Q 400 600, 280 450 Q 150 350, -50 200" />',
  '          <path d="M420 600 Q 550 450, 600 280" strokeWidth="16" />',
  '          <path d="M360 520 Q 420 350, 420 180" strokeWidth="14" />',
  '          <path d="M250 420 Q 150 300, 150 150" strokeWidth="12" />',
  '          <path d="M500 450 Q 650 250, 850 350" strokeWidth="12" />',
  '          <path d="M600 350 Q 700 250, 750 180" strokeWidth="10" />',
  '          <path d="M120 300 Q 50 250, 50 300" strokeWidth="8" />',
  '          <path d="M350 250 Q 320 150, 280 80" strokeWidth="8" />',
  '        </g>',
  '        ',
  '        {/* Embers */}',
  '        {embers.map((ember) => (',
  '          <circle',
  '            key={"ember-" + ember.id}',
  '            cx={ember.cx}',
  '            cy={ember.cy}',
  '            r={ember.r * 2}',
  '            fill={ember.color}',
  '            className="float-particle"',
  '          />',
  '        ))}',
  '',
  '        {/* Glowing Canopy Clusters */}',
  '        {leaves.map((leaf) => (',
  '          <g',
  '            key={leaf.id}',
  '            className="glow-leaf"',
  '            style={{',
  '              transformOrigin: leaf.cx + "px " + leaf.cy + "px",',
  '              animation: "sway " + leaf.swayDuration + "s ease-in-out infinite alternate " + leaf.delay + "s",',
  '            }}',
  '          >',
  '            {/* Radial Gradient Glow (Zero performance cost) */}',
  '            <circle',
  '              cx={leaf.cx}',
  '              cy={leaf.cy}',
  '              r={leaf.r * 4}',
  '              fill={leaf.gradientId}',
  '            />',
  '            {/* Bright Core */}',
  '            <circle',
  '              cx={leaf.cx}',
  '              cy={leaf.cy}',
  '              r={leaf.r}',
  '              fill={leaf.coreColor}',
  '              style={{',
  '                animation: "pulseGlow " + leaf.pulseDuration + "s ease-in-out infinite alternate " + leaf.delay + "s"',
  '              }}',
  '            />',
  '          </g>',
  '        ))}',
  '      </svg>',
  '',
  '      {/* 3D Student Character */}',
  '      <div className="absolute bottom-[2%] right-[5%] z-10 w-96 h-96 character-fade scale-125">',
  '        <svg viewBox="0 0 500 500" fill="none" xmlns="http://www.w3.org/2000/svg">',
  '          <defs>',
  '            <radialGradient id="headGlow" cx="50%" cy="30%" r="50%">',
  '              <stop offset="0%" stopColor="#FFF4D6" />',
  '              <stop offset="70%" stopColor="#D4AF37" />',
  '              <stop offset="100%" stopColor="#8B6F1F" />',
  '            </radialGradient>',
  '            <linearGradient id="bodyGrad" x1="0" y1="0" x2="0" y2="1">',
  '              <stop offset="0%" stopColor="#8B6F1F" />',
  '              <stop offset="100%" stopColor="#0B0A14" />',
  '            </linearGradient>',
  '            <radialGradient id="shadowGlow" cx="50%" cy="50%" r="50%">',
  '              <stop offset="0%" stopColor="rgba(212, 175, 55, 0.3)" />',
  '              <stop offset="100%" stopColor="rgba(212, 175, 55, 0)" />',
  '            </radialGradient>',
  '          </defs>',
  '          ',
  '          {/* Desk / Base */}',
  '          <path d="M120 420 Q 120 250, 250 250 Q 380 250, 380 420 Z" fill="url(#bodyGrad)" />',
  '          ',
  '          {/* Glowing Head */}',
  '          <circle cx="250" cy="180" r="55" fill="url(#headGlow)" />',
  '          ',
  '          {/* Graduation Hat */}',
  '          <path d="M250 115 L 310 135 L 310 160" stroke="#F0D878" strokeWidth="4" fill="none" />',
  '          <circle cx="310" cy="165" r="5" fill="#F0D878" />',
  '          <path d="M190 125 L 310 125 L 290 155 L 210 155 Z" fill="#0B0A14" />',
  '          <path d="M250 90 L 340 125 L 250 160 L 160 125 Z" fill="#1A162B" stroke="#D4AF37" strokeWidth="3" />',
  '          ',
  '          {/* Book */}',
  '          <path d="M180 320 L 320 320 L 300 390 L 200 390 Z" fill="#FFF4D6" />',
  '          <path d="M190 310 L 310 310 L 320 320 L 180 320 Z" fill="#D4AF37" />',
  '          <path d="M250 310 L 250 390" stroke="#8B6F1F" strokeWidth="5" />',
  '          ',
  '          {/* Fast Shadow (no SVG filter) */}',
  '          <circle cx="250" cy="400" r="140" fill="url(#shadowGlow)" />',
  '        </svg>',
  '      </div>',
  '    </div>',
  '  );',
  '}',
].join('\n');

fs.writeFileSync('client/src/components/landing/HeroIllustration.jsx', content, 'utf8');
